kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "socat.fullname" . }}
  labels:
    {{- include "socat.labels" . | nindent 4 }}
data:
  {{ (tpl (.Files.Glob "files/*").AsConfig . ) | nindent 2 }}
