{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "socat.serviceAccountName" . }}
  labels:
{{ include "socat.labels" . | nindent 4 }}
{{- end -}}
