kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "sshd.fullname" . }}
  labels:
    {{- include "sshd.labels" . | nindent 4 }}
    addonmanager.kubernetes.io/mode: Reconcile
data:
  {{- range $user, $args := .Values.users }}
  user-{{ $user }}-keys: |-
    {{ $args.keys }}
  {{- end }}
