kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: {{ include "sshd.fullname" . }}
  labels:
    {{- include "sshd.labels" . | nindent 4 }}
stringData:
  {{- if .Values.ssh.hostkeys.dsa.private }}
  ssh_host_dsa_key: |
    {{- .Values.ssh.hostkeys.dsa.private | nindent 4 }}
  {{ end }}
  {{- if .Values.ssh.hostkeys.dsa.public }}
  ssh_host_dsa_key.pub: {{ .Values.ssh.hostkeys.dsa.public }}
  {{- end }}
  {{- if .Values.ssh.hostkeys.ecdsa.private }}
  ssh_host_ecdsa_key: |
    {{- .Values.ssh.hostkeys.ecdsa.private | nindent 4 }}
  {{ end }}
  {{- if .Values.ssh.hostkeys.ecdsa.public }}
  ssh_host_ecdsa_key.pub: {{ .Values.ssh.hostkeys.ecdsa.public }}
  {{- end }}
  {{- if .Values.ssh.hostkeys.ed25519.private }}
  ssh_host_ed25519_key: |
    {{- .Values.ssh.hostkeys.ed25519.private | nindent 4 }}
  {{ end }}
  {{- if .Values.ssh.hostkeys.ed25519.public }}
  ssh_host_ed25519_key.pub: {{ .Values.ssh.hostkeys.ed25519.public }}
  {{- end }}
  {{- if .Values.ssh.hostkeys.rsa.private }}
  ssh_host_rsa_key: |
    {{- .Values.ssh.hostkeys.rsa.private | nindent 4 }}
  {{ end }}
  {{- if .Values.ssh.hostkeys.rsa.public }}
  ssh_host_rsa_key.pub: {{ .Values.ssh.hostkeys.rsa.public }}
  {{- end }}
