kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: {{ include "proftpd.fullname" . }}
  labels:
    {{- include "proftpd.labels" . | nindent 4 }}
stringData:
  ftpUser:  {{ .Values.proftpd.username | quote }}
  ftpPass:  {{ .Values.proftpd.password | quote }}
  {{ (tpl (.Files.Glob "secret-files/*").AsConfig . ) | nindent 2 }}
