apiVersion: v1
kind: Service
metadata:
  name: {{ include "proftpd.fullname" . }}
  labels:
    {{- include "proftpd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    {{- if .Values.service.ports.ftpData }}
    - name: ftp-data
      port: {{ .Values.service.ports.ftpData }}
      targetPort: ftp-data
      protocol: TCP
    {{- end }}
    - port: {{ .Values.service.ports.ftpCommand }}
      targetPort: ftp
      protocol: TCP
      name: ftp
    {{- range until ( add 1 .Values.service.ports.dynamicCount | int ) }}
    - port: {{ add ( $.Values.service.ports.dynamicStart | int)  . }}
      targetPort: passive{{ . }}
      protocol: TCP
      name: passive{{ . }}
    {{- end }}
  selector:
    {{- include "proftpd.selectorLabels" . | nindent 4 }}
