---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dr-abc.fullname" . }}
  labels:
    {{- include "dr-abc.labels" . | nindent 4 }}
data:
  {{ (tpl (.Files.Glob "scripts/*").AsConfig . ) | nindent 2 }}
