kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dr-abc.fullname" . }}
  labels:
    {{- include "dr-abc.labels" . | nindent 4 }}
rules:
- apiGroups: ['']
  resources:
    - pods
  verbs:
    - get
    - list
    - delete
