kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dr-abc.fullname" . }}
  labels:
    {{- include "dr-abc.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "dr-abc.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "dr-abc.fullname" . }}
