{{- $highAvailability := gt (int .Values.keycloak.replicas) 1 -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "keycloak-export.fullname" . }}-sh
  labels:
    {{- include "keycloak-export.labels" . | nindent 4 }}
data:
  {{ (tpl (.Files.Glob "scripts/*").AsConfig . ) | nindent 2 }}

{{- with .Values.keycloak.shipping.scripts }}
  {{- toYaml . | nindent 2 }}
{{- end }}
