---
{{- if .Values.cert.enabled }}
# Requires Cert-manager
#apiVersion: cert-manager.io/v1
#apiVersion: cert-manager.io/v1alpha2
apiVersion: {{ .Values.cert.certManagerApi }}
kind: Certificate
metadata:
  name: {{ .Values.mail.hostname }}-tls
  labels:
    {{- include "mail-proxy.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.mail.hostname }}-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
    - digital signature
    - key encipherment
    - server auth
  commonName: {{ .Values.mail.hostname }}
  {{- with .Values.cert.subjectAltNames }}
  dnsNames:
    - {{ .Values.mail.hostname }}
    {{- range . }}
    - {{ . }}
    {{- end }}
  {{- end }}
  issuerRef:
    name: {{ .Values.cert.issuer }}
{{- end }}
