kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "mail-proxy.fullname" . }}-nginx
  labels:
    {{- include "mail-proxy.labels" . | nindent 4 }}
data:
  healthcheck: |-
    We are alive
  {{ (tpl (.Files.Glob "files-nginx/*").AsConfig . ) | nindent 2 }}
