{{- if (eq "svc" .Values.mail.phpAuth.type ) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mail-proxy.fullname" . }}-php
  labels:
    {{- include "mail-proxy.phpLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port:       9000
      targetPort: fcgi
      protocol:   TCP
      name:       fcgi
  selector:
    {{- include "mail-proxy.phpSelectorLabels" . | nindent 4 }}
{{- end }}
