{{- if (eq "svc" .Values.mail.phpAuth.type ) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "mail-proxy.fullname" . }}-php
  labels:
    {{- include "mail-proxy.labels" . | nindent 4 }}
stringData:
  {{ (tpl (.Files.Glob "files-php/*").AsConfig . ) | nindent 2 }}
{{- end }}
